name: grades_native_fibonacci_example
description: "Demonstrates how to use the grades_native_fibonacci plugin."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  grades_native_fibonacci:
    path: ../

  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
