// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/grades_native_fibonacci.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class GradesNativeFibonacciBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GradesNativeFibonacciBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GradesNativeFibonacciBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int fib(
    int n,
  ) {
    return _fib(
      n,
    );
  }

  late final _fibPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('fib');
  late final _fib = _fibPtr.asFunction<int Function(int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int fib_long_running(
    int n,
  ) {
    return _fib_long_running(
      n,
    );
  }

  late final _fib_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
          'fib_long_running');
  late final _fib_long_running =
      _fib_long_runningPtr.asFunction<int Function(int)>();
}
